### ISSUE TITLE
windows에서 flask bcrypt 모듈 import 문제 해결.

### ISSUE THREAD

**Issue by hwiba** [baecheese/eungjing#42]
@baecheese 가 해당 모듈 임포트가 안되어 서버를 run 할 수 없는 상태.

**Comment by baecheese** [comment]
# ubuntu 환경으로 변경

flask-bcrypt 설치를 위하여

**libffi-dev** 와 **python-dev**를 apt-get install 명령으로 설치해야 했음.

**Comment by baecheese** [comment]
mysql db 연결을 위해

> sudo pip install PyMySQL
